### PR TITLE
Layout Redesign

### PR DESCRIPTION
**Pull request by HanaeN**
A redesigned layout of the tool, changing the CSS and some of the index.html page to make things look cleaner.

### CODE REVIEW

**Comment by logicplace** [comment]
I only found two issues.

On Firefox there's some overlap for the name box:
name box overlap

Additionally, it seems when you're not logged in there's no credentials box or even an error about not being logged in anymore.

I can take care of this if you need me to?

**Comment by HanaeN** [comment]
If its not too complicated to fix then that would help a lot! I can't test that properly on my end due to needing the request itself to work, didn't mean to accidentally break it though. For the editing box maybe a height can be set on it? just so its uniform across all browsers.

**Comment by logicplace** [comment]
I'd recommend just changing the height of the blue part to be a min-height instead and let it expand for unforseen things like this.

Can you add a username/password placeholder for me so I can put them somewhere? Or maybe we should just make the logged out version have a link to the wiki telling you to log in?

**Comment by HanaeN** [comment]
I went and updated a few of the files to hopefully fix the height and let you test the boxes.

**Comment by logicplace** [comment]
Okay I'm merging this now so I can edit the login stuff myself more easily. Thank you!

**Pull request merged**
